# Generated by Django 5.0.6 on 2024-05-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presidents',
            old_name='pres_num',
            new_name='number',
        ),
    ]
