# Generated by Django 5.0.6 on 2024-05-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_pres_num_presidents_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidents',
            name='description',
            field=models.TextField(default=True, max_length=1000),
        ),
    ]
