# Generated by Django 5.0.6 on 2024-05-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_presidents_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidents',
            name='image',
            field=models.ImageField(default=True, upload_to='static'),
        ),
    ]
